### ISSUE TITLE
[Question] How to include third party libraries (like SDL2 and so on), or to include a prebuilt .so?

### ISSUE THREAD

**Issue by faizol** [arcans1998/ndkbuild-4-androidide#1]
Hi,
Thank you for the very much needed template as a starting point to compile NDK's app directly on a device. 
I've been trying for a few days now to compile a simple GLES2 using SDL2 library to test a full compilation on a device as well as using a prebuilt SDL2 .so lib, but I'm having problems ranging from SDL_main entry problem to app unable to open libSDL2.so. The program could run properly if I compile it on my host machine and install it on a device. 

Any hint on a proper way to include a SDL2 library in Android.mk or others?

Cheers,

**Comment by faizol** [comment]
Sorry for the noise. I found several references on the issue, hopefully I can get the solution for the above problem. Tq.

**Comment by arcans-dev-ph** [comment]
https://github.com/Lzhiyong/termux-sdl
